# Generated by Django 2.2.13 on 2020-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
